title: "Jalal Khan Utman"
name: "Jalal Khan Utman"
description: "Biotechnology researcher focused on neuro-oncology, molecular modeling, cell based assays, nanoparticle research, and scientific communication."
email: "hello@jalalkhan.me"
url: "https://jalalkhan.me"
baseurl: ""

linkedin_url: "https://www.linkedin.com/in/jalal-khan-utman-56bb83193"
github_username: "jalalkhanutmanzai"

timezone: UTC
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope:
      path: ""
    values:
      layout: page
